const conform = require('../conform-schema')

const baseStats = {
  team_id: '5ec9358d8c0dd900074685c1',
  team_name: 'Burnsville Inferno',
  opponent_team_id: '5ec9358e8c0dd900074685c3',
  opponent_team_name: 'Hibbing Rangers',
  team_color: 'orange',
  league_name: 'mncs',
  league_id: '5ec9359b8c0dd900074686d3',
  match_id: '5ec935988c0dd900074686ae',
  match_type: 'REG',
  season_name: '1',
  season_id: '5ec935998c0dd900074686d2',
  week: 2,
  game_id: '5ec935958c0dd9000746863c',
  game_date: '2020-04-04T18:56:14Z',
  game_number: '1',
  map_name: 'DFH Stadium',
  wins: 0,
  game_id_total: 'match:5ec935988c0dd900074686ae:game:1',
  ms_played: 352000,
  shots: 5,
  opponent_shots: 7,
  shots_against: 7,
  opponent_shots_against: 5,
  goals: 2,
  opponent_goals: 3,
  goals_against: 3,
  opponent_goals_against: 2,
  saves: 3,
  opponent_saves: 2,
  assists: 1,
  opponent_assists: 1,
  score: 890,
  opponent_score: 974,
  shooting_percentage: 40,
  opponent_shooting_percentage: 42.857143,
  bpm: 1288,
  opponent_bpm: 1074,
  bcpm: 1249.6337,
  opponent_bcpm: 1139.0974,
  avg_amount: 129.39001,
  opponent_avg_amount: 153.22,
  amount_collected: 6964,
  opponent_amount_collected: 6348,
  amount_stolen: 1381,
  opponent_amount_stolen: 1422,
  amount_collected_big: 4890,
  opponent_amount_collected_big: 4279,
  amount_stolen_big: 767,
  opponent_amount_stolen_big: 787,
  amount_collected_small: 2074,
  opponent_amount_collected_small: 2069,
  amount_stolen_small: 614,
  opponent_amount_stolen_small: 635,
  count_collected_big: 55,
  opponent_count_collected_big: 53,
  count_stolen_big: 9,
  opponent_count_stolen_big: 9,
  count_collected_small: 189,
  opponent_count_collected_small: 182,
  count_stolen_small: 54,
  opponent_count_stolen_small: 51,
  amount_overfill: 652,
  opponent_amount_overfill: 862,
  amount_overfill_stolen: 131,
  opponent_amount_overfill_stolen: 131,
  amount_used_while_supersonic: 1193,
  opponent_amount_used_while_supersonic: 676,
  ms_zero_boost: 130560,
  opponent_ms_zero_boost: 95530,
  ms_full_boost: 79990,
  opponent_ms_full_boost: 101479.996,
  ms_boost_0_25: 401780,
  opponent_ms_boost_0_25: 368730,
  ms_boost_25_50: 251350,
  opponent_ms_boost_25_50: 224799.99000000002,
  ms_boost_50_75: 170820,
  opponent_ms_boost_50_75: 223070,
  ms_boost_75_100: 189280,
  opponent_ms_boost_75_100: 213540.01,
  total_distance: 1588443,
  opponent_total_distance: 1553481,
  ms_supersonic_speed: 175080,
  opponent_ms_supersonic_speed: 119509.99500000001,
  ms_boost_speed: 451030,
  opponent_ms_boost_speed: 503030,
  ms_slow_speed: 426320,
  opponent_ms_slow_speed: 426930,
  ms_ground: 578170,
  opponent_ms_ground: 600970,
  ms_low_air: 418360.02,
  opponent_ms_low_air: 394320,
  ms_high_air: 55890,
  opponent_ms_high_air: 54180,
  ms_powerslide: 22640,
  opponent_ms_powerslide: 22130.001,
  count_powerslide: 200,
  opponent_count_powerslide: 210,
  ms_defensive_third: 493330,
  opponent_ms_defensive_third: 457600,
  ms_neutral_third: 350290,
  opponent_ms_neutral_third: 379479.98000000004,
  ms_offensive_third: 208810,
  opponent_ms_offensive_third: 212380,
  ms_defensive_half: 678270,
  opponent_ms_defensive_half: 678050,
  ms_offensive_half: 374159.97,
  opponent_ms_offensive_half: 371410,
  ms_behind_ball: 733810,
  opponent_ms_behind_ball: 741170.0399999999,
  ms_infront_ball: 318620,
  opponent_ms_infront_ball: 308300,
  demos_inflicted: 2,
  opponent_demos_inflicted: 1,
  demos_taken: 1,
  opponent_demos_taken: 2,
}

const baseSchema = [
  { name: 'team_id', type: { default: 'string' } },
  { name: 'opponent_team_id', type: { default: 'string' } },
  { name: 'team_name', type: { default: 'string' } },
  { name: 'opponent_team_name', type: { default: 'string' } },
  { name: 'team_color', type: { default: 'string' } },
  { name: 'opponent_team_color', type: { default: 'string' } },
  { name: 'league_name', type: { default: 'string' } },
  { name: 'opponent_league_name', type: { default: 'string' } },
  { name: 'league_id', type: { default: 'string' } },
  { name: 'opponent_league_id', type: { default: 'string' } },
  { name: 'match_id', type: { default: 'string' } },
  { name: 'opponent_match_id', type: { default: 'string' } },
  { name: 'match_type', type: { default: 'string' } },
  { name: 'opponent_match_type', type: { default: 'string' } },
  { name: 'season_name', type: { default: 'string' } },
  { name: 'opponent_season_name', type: { default: 'string' } },
  { name: 'season_id', type: { default: 'string' } },
  { name: 'opponent_season_id', type: { default: 'string' } },
  { name: 'week', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_week', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'game_id', type: { default: 'string' } },
  { name: 'opponent_game_id', type: { default: 'string' } },
  { name: 'game_date', type: { default: 'timestamp' } },
  { name: 'opponent_game_date', type: { default: 'timestamp' } },
  { name: 'game_number', type: { default: 'string' } },
  { name: 'opponent_game_number', type: { default: 'string' } },
  { name: 'map_name', type: { default: 'string' } },
  { name: 'opponent_map_name', type: { default: 'string' } },
  { name: 'match_id_win', type: { default: 'string' } },
  { name: 'opponent_match_id_win', type: { default: 'string' } },
  { name: 'game_id_win', type: { default: 'string' } },
  { name: 'opponent_game_id_win', type: { default: 'string' } },
  { name: 'game_id_forfeit_win', type: { default: 'string' } },
  { name: 'opponent_game_id_forfeit_win', type: { default: 'string' } },
  { name: 'wins', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_wins', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_played', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_played', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'shots', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_shots', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'shots_against', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_shots_against', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'goals', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_goals', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'goals_against', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_goals_against', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'saves', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_saves', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'assists', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_assists', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'score', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_score', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'amount_collected', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_amount_collected', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'amount_stolen', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_amount_stolen', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'amount_collected_big', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_amount_collected_big', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'amount_stolen_big', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_amount_stolen_big', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'amount_collected_small', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_amount_collected_small', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'amount_stolen_small', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_amount_stolen_small', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'count_collected_big', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_count_collected_big', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'count_stolen_big', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_count_stolen_big', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'count_collected_small', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_count_collected_small', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'count_stolen_small', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_count_stolen_small', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'amount_overfill', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_amount_overfill', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'amount_overfill_stolen', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_amount_overfill_stolen', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'amount_used_while_supersonic', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_amount_used_while_supersonic', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_zero_boost', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_zero_boost', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_full_boost', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_full_boost', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_boost_0_25', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_boost_0_25', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_boost_25_50', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_boost_25_50', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_boost_50_75', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_boost_50_75', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_boost_75_100', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_boost_75_100', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'total_distance', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_total_distance', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_supersonic_speed', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_supersonic_speed', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_boost_speed', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_boost_speed', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_slow_speed', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_slow_speed', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_ground', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_ground', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_low_air', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_low_air', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_high_air', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_high_air', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_powerslide', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_powerslide', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'count_powerslide', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_count_powerslide', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_defensive_third', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_defensive_third', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_neutral_third', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_neutral_third', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_offensive_third', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_offensive_third', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_defensive_half', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_defensive_half', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_offensive_half', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_offensive_half', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_behind_ball', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_behind_ball', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'ms_infront_ball', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_ms_infront_ball', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'demos_inflicted', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_demos_inflicted', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'demos_taken', type: { DDL: 'INT64', default: 'integer' } },
  { name: 'opponent_demos_taken', type: { DDL: 'INT64', default: 'integer' } },
]

describe('conform-schema', () => {
  it('should reduce an object to match the schema keys', () => {
    const result = conform(baseStats, baseSchema)
    expect(result).toMatchObject({
      goals_against: 3,
      opponent_goals_against: 2,
    })
    expect(result).not.toHaveProperty('shooting_percentage')
  })
  it('should convert integers', () => {
    const result = conform(baseStats, baseSchema)
    expect(result).toMatchObject({
      opponent_ms_full_boost: 101480,
      opponent_ms_supersonic_speed: 119510,
    })
  })
  it('should conform arrays', () => {
    const result = conform([baseStats, baseStats], baseSchema)
    expect(result).toBeInstanceOf(Array)
    expect(result).toMatchObject([
      {
        goals_against: 3,
        opponent_goals_against: 2,
      },
      {
        goals_against: 3,
        opponent_goals_against: 2,
      },
    ])
  })
})
