const router = require('express').Router()
const override = require('method-override')

const attachModel = require('./attach-model')
const errorHandler = require('./errors')
const { Model: Teams } = require('../../model/mongodb/teams')
const { Model: Players } = require('../../model/mongodb/players')
const { Model: Leagues } = require('../../model/mongodb/leagues')
const { Model: Seasons } = require('../../model/mongodb/seasons')
const { Model: Matches } = require('../../model/mongodb/matches')
const { Model: Games } = require('../../model/mongodb/games')

router.use(require('./modify-request'))
router.use('/events', require('./events'))
router.use('/teams', attachModel(Teams))
router.use('/players', attachModel(Players))
router.use('/leagues', attachModel(Leagues))
router.use('/seasons', attachModel(Seasons))
router.use('/seasons/:season_id/standings', require('./standings'))
router.use('/matches', attachModel(Matches))
router.use('/games', attachModel(Games))
router.use('/stats', require('./stats'))
router.use(require('./send-request'))
router.use(override())
router.use(errorHandler)

module.exports = router
