service: rl-stats

plugins:
  - serverless-python-requirements
  - serverless-offline

package:
  exclude:
    - node_modules/**/aws-sdk/**
    - ./src/**/*.spec.*
    - test
    - .eslintrc*
    - .prettierrc*
    - .vscode*
    - README*
    - __test__/**
    - temp/**

custom:
  pythonRequirements:
    dockerizePip: true
    usePipenv: true
    # useDownloadCache: false
    # useStaticCache: false

provider:
  name: aws
  runtime: python3.6
  profile: personal
  region: us-east-1
  stage: dev
  environment:
    SERVERLESS_REGION: ${opt:region,self:provider.region}
    SERVERLESS_STAGE: ${self:provider.stage}
    BALLCHASING_KEY: ${ssm:BALLCHASING_KEY}

functions:
  process-game:
    handler: lambdas/process-game.handler
    memorySize: 3008
    timeout: 10
  fetch-ranks:
    handler: lambdas/fetch-ranks.handler
    runtime: nodejs10.x
    events:
      - http:
          path: /ranks/{platform}/{platformId}
          method: get
          cors: true
          request:
            parameters:
              path:
                platform: true
                platformId: true
  fetch-games:
    handler: lambdas/fetch-games.handler
    runtime: nodejs10.x
    events:
      - http:
          path: /games
          method: get
          cors: true
