service: rl-stats

plugins:
  # - serverless-python-requirements
  - serverless-export-env
  - serverless-dotenv-plugin
  - serverless-step-functions
  - serverless-offline

package:
  exclude:
    - node_modules/**/aws-sdk/**
    - ./src/**/*.spec.*
    - test
    - .eslintrc*
    - .prettierrc*
    - .vscode*
    - README*
    - __test__/**
    - temp/**
    - .env

custom:
  dev:
    dbSecret: rds-db-credentials/cluster-7D5M6AOKEDM4X7ASP7PTQME3BQ/root

provider:
  name: aws
  runtime: nodejs10.x
  profile: personal
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  endpointType: REGIONAL
  environment:
    SERVERLESS_REGION: ${self:provider.region}
    SERVERLESS_STAGE: ${self:provider.stage}
    SERVERLESS_ACCOUNT_ID:
      Ref: AWS::AccountId
    BALLCHASING_KEY: ${ssm:BALLCHASING_KEY}
    MNCS_STAT_SHEET_ID: ${ssm:${self:provider.stage}-MNCS_STAT_SHEET_ID}
    MNRL_SHEET_ID: ${ssm:${self:provider.stage}-MNRL_SHEET_ID}
    MATCH_STATE_MACHINE_ARN: ${self:resources.Outputs.MatchPollerArn.Value}
    GAMES_QUEUE_URL:
      Ref: GamesQueue
  vpc:
    securityGroupIds:
      - sg-bd8bb2e1
    subnetIds:
      - subnet-935a77cf
      - subnet-809565cd
      - subnet-6a406f44
      - subnet-d37e0aed
      - subnet-c64b51c9
      - subnet-28af8e4f
  iamRoleStatements:
    - Effect: Allow
      Action:
        - states:StartExecution
        - s3:*
        - dynamodb:*
        - rds:*
      Resource:
        - '*'
    - Effect: Allow
      Action:
        - sqs:ListQueues
        - sqs:DeleteMessage
        - sqs:GetQueueUrl
        - sqs:ReceiveMessage
        - sqs:SendMessage
      Resource:
        - '*'
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: 
        - '*'
  usagePlan:
    quota:
      limit: 10000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 10
      rateLimit: 5

functions:
  # analyzes a replay file and produces its stats
  process-game:
    handler: lambdas/process-game.handler
    name: ${self:service}-process-game-${self:provider.stage}
    memorySize: 3008
    timeout: 10

  # fetches a player's ranks via https://rocketleague.tracker.network/
  fetch-ranks:
    handler: lambdas/fetch-ranks.handler
    name: ${self:service}-fetch-ranks-${self:provider.stage}
    runtime: nodejs10.x
    events:
      - http:
          path: /ranks/{platform}/{platformId}
          method: get
          cors: true
          request:
            parameters:
              path:
                platform: true
                platformId: true

  # see query parameter options here https://ballchasing.com/doc/api#replays
  fetch-games:
    handler: lambdas/fetch-games.handler
    name: ${self:service}-fetch-games-${self:provider.stage}
    runtime: nodejs10.x
    events:
      - http:
          path: /games
          method: get
          cors: true

  report-games:
    handler: lambdas/report-games.handler
    name: ${self:service}-report-games-${self:provider.stage}
    runtime: nodejs10.x
    timeout: 30
    events:
      - http:
          path: /games/_report
          method: post
          private: true
          cors: true

  reprocess-games:
    handler: lambdas/reprocess-games.handler
    name: ${self:service}-reprocess-games-${self:provider.stage}
    runtime: nodejs10.x
    timeout: 30
    events:
      - http:
          path: /games/_reprocess
          method: post
          private: true
          cors: true
  
  process-match:
    handler: lambdas/process-match.handler
    name: ${self:service}-process-match-${self:provider.stage}
    runtime: nodejs10.x
    timeout: 30
    reservedConcurrency: 1
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - GamesQueue
              - Arn
          batchSize: 1

  authorize:
    handler: lambdas/authorize.handler
    name: ${self:service}-authorize-${self:provider.stage}
    runtime: nodejs10.x

  rest-api:
    handler: lambdas/rest-api.handler
    name: ${self:service}-rest-api-${self:provider.stage}
    runtime: nodejs10.x
    timeout: 30
    events:
      - http:
          path: /api/{table}
          method: get
          # authorizer: authorize
          cors: true
          private: true
      - http:
          path: /api/{table}
          method: put
          cors: true
          private: true
  
  init-step-function:
    handler: lambdas/init-step-function.handler
    name: ${self:service}-init-step-function-${self:provider.stage}
    runtime: nodejs10.x

  migrate:
    handler: lambdas/migrate.handler
    name: ${self:service}-migrate-${self:provider.stage}
    runtime: nodejs10.x
    timeout: 300

stepFunctions:
  stateMachines:
    MatchReader:
      name: MatchPoller-${self:provider.stage}
      definition:
        StartAt: retrieve-match-results
        States:
          retrieve-match-results:
            Type: Task
            # Next: is-match-closed
            End: true
            Resource:
              Fn::Join:
                - ":"
                - - arn:aws:lambda
                  - Ref: 'AWS::Region'
                  - Ref: 'AWS::AccountId'
                  - function:${self:service}-fetch-games-${self:provider.stage}
            TimeoutSeconds: 300
          # is-match-closed:
          #   Type: Choice
          #   Choices:
          #     - Variable: $.closed
          #         NumericGreaterThan: 0
          #         Next: save-match-results

resources:
  Resources:
    AuthTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: auth-table-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    GamesQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-process-games-queue-${self:provider.stage}
        DelaySeconds: 0
        MessageRetentionPeriod: 345600
        ReceiveMessageWaitTimeSeconds: 20
        VisibilityTimeout: 40
  Outputs:
    MatchPollerArn:
      Description: The arn for the match polling state machine
      Value:
        Ref: MatchPollerDash${self:provider.stage} # Dash is used to replace '-' in local state machine name
    GamesQueue:
      Value:
        Ref: GamesQueue