const types = require('./types')
const opponent = require('./opponent')
const gameContext = require('./contexts/game_context')
const teamContext = require('./contexts/team_context')

const teamStats = [
  ...gameContext,
  ...teamContext,
  { name: 'wins', type: types.INT },
  { name: 'ms_played', type: types.INT },
  { name: 'shots', type: types.INT },
  { name: 'shots_against', type: types.INT },
  { name: 'goals', type: types.INT },
  { name: 'goals_against', type: types.INT },
  { name: 'saves', type: types.INT },
  { name: 'assists', type: types.INT },
  { name: 'score', type: types.INT },
  { name: 'amount_collected', type: types.INT },
  { name: 'amount_stolen', type: types.INT },
  { name: 'amount_collected_big', type: types.INT },
  { name: 'amount_stolen_big', type: types.INT },
  { name: 'amount_collected_small', type: types.INT },
  { name: 'amount_stolen_small', type: types.INT },
  { name: 'count_collected_big', type: types.INT },
  { name: 'count_stolen_big', type: types.INT },
  { name: 'count_collected_small', type: types.INT },
  { name: 'count_stolen_small', type: types.INT },
  { name: 'amount_overfill', type: types.INT },
  { name: 'amount_overfill_stolen', type: types.INT },
  { name: 'amount_used_while_supersonic', type: types.INT },
  { name: 'ms_zero_boost', type: types.INT },
  { name: 'ms_full_boost', type: types.INT },
  { name: 'ms_boost_0_25', type: types.INT },
  { name: 'ms_boost_25_50', type: types.INT },
  { name: 'ms_boost_50_75', type: types.INT },
  { name: 'ms_boost_75_100', type: types.INT },
  { name: 'total_distance', type: types.INT },
  { name: 'ms_supersonic_speed', type: types.INT },
  { name: 'ms_boost_speed', type: types.INT },
  { name: 'ms_slow_speed', type: types.INT },
  { name: 'ms_ground', type: types.INT },
  { name: 'ms_low_air', type: types.INT },
  { name: 'ms_high_air', type: types.INT },
  { name: 'ms_powerslide', type: types.INT },
  { name: 'count_powerslide', type: types.INT },
  { name: 'ms_defensive_third', type: types.INT },
  { name: 'ms_neutral_third', type: types.INT },
  { name: 'ms_offensive_third', type: types.INT },
  { name: 'ms_defensive_half', type: types.INT },
  { name: 'ms_offensive_half', type: types.INT },
  { name: 'ms_behind_ball', type: types.INT },
  { name: 'ms_infront_ball', type: types.INT },
  { name: 'demos_inflicted', type: types.INT },
  { name: 'demos_taken', type: types.INT },
]

module.exports = opponent(teamStats)
