module.exports = {
  mncs: [
    [
      { teams: ['ROCHESTER RHYTHM', 'BURNSVILLE INFERNO'] },
      { teams: ['BEMIDJI LUMBERJACKS', 'MINNETONKA BARONS'] },
      { teams: ['ST. PAUL SENATORS', 'HIBBING RANGERS'] },
      { teams: ['ST. CLOUD FLYERS', 'DULUTH SUPERIORS'] },
      { teams: ['BLOOMINGTON MAULERS', 'MINNEAPOLIS MIRACLES'] },
    ],
    [
      { teams: ['HIBBING RANGERS', 'MINNETONKA BARONS'] },
      { teams: ['BLOOMINGTON MAULERS', 'ROCHESTER RHYTHM'] },
      { teams: ['ST. CLOUD FLYERS', 'MINNEAPOLIS MIRACLES'] },
      { teams: ['ST. PAUL SENATORS', 'DULUTH SUPERIORS'] },
      { teams: ['BEMIDJI LUMBERJACKS', 'BURNSVILLE INFERNO'] },
    ],
    [
      { teams: ['HIBBING RANGERS', 'BEMIDJI LUMBERJACKS'] },
      { teams: ['BLOOMINGTON MAULERS', 'ST. PAUL SENATORS'] },
      { teams: ['DULUTH SUPERIORS', 'ROCHESTER RHYTHM'] },
      { teams: ['MINNETONKA BARONS', 'ST. CLOUD FLYERS'] },
      { teams: ['BURNSVILLE INFERNO', 'MINNEAPOLIS MIRACLES'] },
    ],
    [
      { teams: ['BLOOMINGTON MAULERS', 'ST. CLOUD FLYERS'] },
      { teams: ['BEMIDJI LUMBERJACKS', 'ROCHESTER RHYTHM'] },
      { teams: ['HIBBING RANGERS', 'BURNSVILLE INFERNO'] },
      { teams: ['MINNETONKA BARONS', 'DULUTH SUPERIORS'] },
      { teams: ['ST. PAUL SENATORS', 'MINNEAPOLIS MIRACLES'] },
    ],
    [
      { teams: ['ST. PAUL SENATORS', 'MINNETONKA BARONS'] },
      { teams: ['DULUTH SUPERIORS', 'BEMIDJI LUMBERJACKS'] },
      { teams: ['BLOOMINGTON MAULERS', 'HIBBING RANGERS'] },
      { teams: ['BURNSVILLE INFERNO', 'ST. CLOUD FLYERS'] },
      { teams: ['MINNEAPOLIS MIRACLES', 'ROCHESTER RHYTHM'] },
    ],
    [
      { teams: ['ROCHESTER RHYTHM', 'MINNETONKA BARONS'] },
      { teams: ['BEMIDJI LUMBERJACKS', 'ST. PAUL SENATORS'] },
      { teams: ['MINNEAPOLIS MIRACLES', 'DULUTH SUPERIORS'] },
      { teams: ['BLOOMINGTON MAULERS', 'BURNSVILLE INFERNO'] },
      { teams: ['ST. CLOUD FLYERS', 'HIBBING RANGERS'] },
    ],
    [
      { teams: ['ROCHESTER RHYTHM', 'ST. CLOUD FLYERS'] },
      { teams: ['MINNEAPOLIS MIRACLES', 'BEMIDJI LUMBERJACKS'] },
      { teams: ['BURNSVILLE INFERNO', 'ST. PAUL SENATORS'] },
      { teams: ['DULUTH SUPERIORS', 'HIBBING RANGERS'] },
      { teams: ['BLOOMINGTON MAULERS', 'MINNETONKA BARONS'] },
    ],
    [
      { teams: ['ST. PAUL SENATORS', 'ST. CLOUD FLYERS'] },
      { teams: ['BLOOMINGTON MAULERS', 'BEMIDJI LUMBERJACKS'] },
      { teams: ['HIBBING RANGERS', 'ROCHESTER RHYTHM'] },
      { teams: ['DULUTH SUPERIORS', 'BURNSVILLE INFERNO'] },
      { teams: ['MINNETONKA BARONS', 'MINNEAPOLIS MIRACLES'] },
    ],
    [
      { teams: ['ST. CLOUD FLYERS', 'BEMIDJI LUMBERJACKS'] },
      { teams: ['ROCHESTER RHYTHM', 'ST. PAUL SENATORS'] },
      { teams: ['MINNEAPOLIS MIRACLES', 'HIBBING RANGERS'] },
      { teams: ['MINNETONKA BARONS', 'BURNSVILLE INFERNO'] },
      { teams: ['BLOOMINGTON MAULERS', 'DULUTH SUPERIORS'] },
    ],
  ],
  clmn: [
    [
      { teams: ['PILLAGER PIRATES', 'COTTAGE GROVE CRIMSON WINGS'] },
      { teams: ['NEW BRIGHTON NORDICS', 'MANKATO MONKEYS'] },
      { teams: ['WHITE BEAR LAKERS', 'PRIOR LAKE PENGUINS'] },
      { teams: ['SAVAGE BOOSTY BOYS', 'MOORHEAD IMPORTS'] },
      { teams: ['BLAINE BAGUETTES', 'DULUTH GRANDMAS'] },
      { teams: ['VADNAIS VANDALS', 'BROOKLYN PARK RAPTORS'] },
    ],
    [
      { teams: ['PILLAGER PIRATES', 'MANKATO MONKEYS'] },
      { teams: ['NEW BRIGHTON NORDICS', 'BROOKLYN PARK RAPTORS'] },
      { teams: ['WHITE BEAR LAKERS', 'MOORHEAD IMPORTS'] },
      { teams: ['SAVAGE BOOSTY BOYS', 'DULUTH GRANDMAS'] },
      { teams: ['BLAINE BAGUETTES', 'PRIOR LAKE PENGUINS'] },
      { teams: ['VADNAIS VANDALS', 'COTTAGE GROVE CRIMSON WINGS'] },
    ],
    [
      { teams: ['PILLAGER PIRATES', 'MOORHEAD IMPORTS'] },
      { teams: ['NEW BRIGHTON NORDICS', 'PRIOR LAKE PENGUINS'] },
      { teams: ['WHITE BEAR LAKERS', 'MANKATO MONKEYS'] },
      { teams: ['SAVAGE BOOSTY BOYS', 'COTTAGE GROVE CRIMSON WINGS'] },
      { teams: ['BLAINE BAGUETTES', 'BROOKLYN PARK RAPTORS'] },
      { teams: ['VADNAIS VANDALS', 'DULUTH GRANDMAS'] },
    ],
    [
      { teams: ['PILLAGER PIRATES', 'VADNAIS VANDALS'] },
      { teams: ['NEW BRIGHTON NORDICS', 'BLAINE BAGUETTES'] },
      { teams: ['WHITE BEAR LAKERS', 'SAVAGE BOOSTY BOYS'] },
      { teams: ['MOORHEAD IMPORTS', 'DULUTH GRANDMAS'] },
      { teams: ['PRIOR LAKE PENGUINS', 'BROOKLYN PARK RAPTORS'] },
      { teams: ['MANKATO MONKEYS', 'COTTAGE GROVE CRIMSON WINGS'] },
    ],
    [
      { teams: ['PILLAGER PIRATES', 'BLAINE BAGUETTES'] },
      { teams: ['NEW BRIGHTON NORDICS', 'WHITE BEAR LAKERS'] },
      { teams: ['SAVAGE BOOSTY BOYS', 'VADNAIS VANDALS'] },
      { teams: ['MOORHEAD IMPORTS', 'BROOKLYN PARK RAPTORS'] },
      { teams: ['PRIOR LAKE PENGUINS', 'MANKATO MONKEYS'] },
      { teams: ['COTTAGE GROVE CRIMSON WINGS', 'DULUTH GRANDMAS'] },
    ],
    [
      { teams: ['PILLAGER PIRATES', 'SAVAGE BOOSTY BOYS'] },
      { teams: ['NEW BRIGHTON NORDICS', 'VADNAIS VANDALS'] },
      { teams: ['WHITE BEAR LAKERS', 'BLAINE BAGUETTES'] },
      { teams: ['MOORHEAD IMPORTS', 'COTTAGE GROVE CRIMSON WINGS'] },
      { teams: ['PRIOR LAKE PENGUINS', 'DULUTH GRANDMAS'] },
      { teams: ['MANKATO MONKEYS', 'BROOKLYN PARK RAPTORS'] },
    ],
    [
      { teams: ['PILLAGER PIRATES', 'WHITE BEAR LAKERS'] },
      { teams: ['NEW BRIGHTON NORDICS', 'SAVAGE BOOSTY BOYS'] },
      { teams: ['BLAINE BAGUETTES', 'VADNAIS VANDALS'] },
      { teams: ['MOORHEAD IMPORTS', 'MANKATO MONKEYS'] },
      { teams: ['PRIOR LAKE PENGUINS', 'COTTAGE GROVE CRIMSON WINGS'] },
      { teams: ['BROOKLYN PARK RAPTORS', 'DULUTH GRANDMAS'] },
    ],
    [
      { teams: ['PILLAGER PIRATES', 'NEW BRIGHTON NORDICS'] },
      { teams: ['WHITE BEAR LAKERS', 'VADNAIS VANDALS'] },
      { teams: ['SAVAGE BOOSTY BOYS', 'BLAINE BAGUETTES'] },
      { teams: ['MOORHEAD IMPORTS', 'PRIOR LAKE PENGUINS'] },
      { teams: ['MANKATO MONKEYS', 'DULUTH GRANDMAS'] },
      { teams: ['COTTAGE GROVE CRIMSON WINGS', 'BROOKLYN PARK RAPTORS'] },
    ],
  ],
  clmnTeams: [
    'Pillager Pirates',
    'Cottage Grove Crimson Wings',
    'New Brighton Nordics',
    'Mankato Monkeys',
    'White Bear Lakers',
    'Prior Lake Penguins',
    'Savage Boosty Boys',
    'Moorhead Imports',
    'Blaine Baguettes',
    'Duluth Grandmas',
    'Vadnais Vandals',
    'Brooklyn Park Raptors',
  ],
}
