process.env.PRODUCED_STATS_BUCKET = 'stats_bucket_name'
process.env.SERVERLESS_STAGE = 'test'
process.env.REPLAY_FILES_BUCKET = 'mock-bucket'
process.env.LIVE_STATS_BUCKET = 'tester-bucket'
process.env.LIVE_STATS_CHANNEL_ID = '692994579305332806'
process.env.SERVERLESS_STAGE = 'test'
